/// Reference lists for the organization sign-up form: ISO 3166-1 countries,
/// their principal subdivisions, and IANA time zones.
///
/// Held here rather than pulled from a package: the form needs names and codes
/// only, and a dependency for static text would have to be kept current
/// anyway. Subdivisions are listed for the countries the product sells into;
/// everywhere else falls back to free text, which is why [statesOf] may return
/// an empty list.
library;

/// ISO 3166-1 countries, alpha-2 code to display name.
const Map<String, String> countries = {
  'AF': 'Afghanistan',
  'AL': 'Albania',
  'DZ': 'Algeria',
  'AR': 'Argentina',
  'AM': 'Armenia',
  'AU': 'Australia',
  'AT': 'Austria',
  'AZ': 'Azerbaijan',
  'BH': 'Bahrain',
  'BD': 'Bangladesh',
  'BY': 'Belarus',
  'BE': 'Belgium',
  'BO': 'Bolivia',
  'BA': 'Bosnia and Herzegovina',
  'BW': 'Botswana',
  'BR': 'Brazil',
  'BG': 'Bulgaria',
  'KH': 'Cambodia',
  'CM': 'Cameroon',
  'CA': 'Canada',
  'CL': 'Chile',
  'CN': 'China',
  'CO': 'Colombia',
  'CR': 'Costa Rica',
  'HR': 'Croatia',
  'CY': 'Cyprus',
  'CZ': 'Czechia',
  'DK': 'Denmark',
  'DO': 'Dominican Republic',
  'EC': 'Ecuador',
  'EG': 'Egypt',
  'SV': 'El Salvador',
  'EE': 'Estonia',
  'ET': 'Ethiopia',
  'FI': 'Finland',
  'FR': 'France',
  'GE': 'Georgia',
  'DE': 'Germany',
  'GH': 'Ghana',
  'GR': 'Greece',
  'GT': 'Guatemala',
  'HN': 'Honduras',
  'HK': 'Hong Kong',
  'HU': 'Hungary',
  'IS': 'Iceland',
  'IN': 'India',
  'ID': 'Indonesia',
  'IQ': 'Iraq',
  'IE': 'Ireland',
  'IL': 'Israel',
  'IT': 'Italy',
  'JM': 'Jamaica',
  'JP': 'Japan',
  'JO': 'Jordan',
  'KZ': 'Kazakhstan',
  'KE': 'Kenya',
  'KW': 'Kuwait',
  'LV': 'Latvia',
  'LB': 'Lebanon',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'MY': 'Malaysia',
  'MT': 'Malta',
  'MU': 'Mauritius',
  'MX': 'Mexico',
  'MA': 'Morocco',
  'MM': 'Myanmar',
  'NP': 'Nepal',
  'NL': 'Netherlands',
  'NZ': 'New Zealand',
  'NG': 'Nigeria',
  'NO': 'Norway',
  'OM': 'Oman',
  'PK': 'Pakistan',
  'PA': 'Panama',
  'PY': 'Paraguay',
  'PE': 'Peru',
  'PH': 'Philippines',
  'PL': 'Poland',
  'PT': 'Portugal',
  'QA': 'Qatar',
  'RO': 'Romania',
  'RU': 'Russia',
  'SA': 'Saudi Arabia',
  'SN': 'Senegal',
  'RS': 'Serbia',
  'SG': 'Singapore',
  'SK': 'Slovakia',
  'SI': 'Slovenia',
  'ZA': 'South Africa',
  'KR': 'South Korea',
  'ES': 'Spain',
  'LK': 'Sri Lanka',
  'SE': 'Sweden',
  'CH': 'Switzerland',
  'TW': 'Taiwan',
  'TZ': 'Tanzania',
  'TH': 'Thailand',
  'TN': 'Tunisia',
  'TR': 'Türkiye',
  'UG': 'Uganda',
  'UA': 'Ukraine',
  'AE': 'United Arab Emirates',
  'GB': 'United Kingdom',
  'US': 'United States',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistan',
  'VN': 'Vietnam',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe',
};

/// Principal subdivisions, by ISO 3166-1 alpha-2 country code. Countries absent
/// here take a free-text state — see [statesOf].
const Map<String, List<String>> _states = {
  'IN': [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chandigarh',
    'Chhattisgarh',
    'Delhi',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Puducherry',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
  ],
  'US': [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'District of Columbia',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
  ],
  'CA': [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Northwest Territories',
    'Nova Scotia',
    'Nunavut',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
    'Yukon',
  ],
  'AU': [
    'Australian Capital Territory',
    'New South Wales',
    'Northern Territory',
    'Queensland',
    'South Australia',
    'Tasmania',
    'Victoria',
    'Western Australia',
  ],
  'GB': ['England', 'Northern Ireland', 'Scotland', 'Wales'],
  'DE': [
    'Baden-Württemberg',
    'Bavaria',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hesse',
    'Lower Saxony',
    'Mecklenburg-Vorpommern',
    'North Rhine-Westphalia',
    'Rhineland-Palatinate',
    'Saarland',
    'Saxony',
    'Saxony-Anhalt',
    'Schleswig-Holstein',
    'Thuringia',
  ],
  'AE': [
    'Abu Dhabi',
    'Ajman',
    'Dubai',
    'Fujairah',
    'Ras Al Khaimah',
    'Sharjah',
    'Umm Al Quwain',
  ],
  'SG': ['Central', 'East', 'North', 'North-East', 'West'],
};

/// Subdivisions for [countryCode], or an empty list when the country takes a
/// free-text state.
List<String> statesOf(String? countryCode) =>
    _states[countryCode] ?? const [];

/// IANA time zones with their standard UTC offsets, ordered west to east.
const List<String> timeZones = [
  'Pacific/Midway (UTC−11:00)',
  'Pacific/Honolulu (UTC−10:00)',
  'America/Anchorage (UTC−09:00)',
  'America/Los_Angeles (UTC−08:00)',
  'America/Denver (UTC−07:00)',
  'America/Chicago (UTC−06:00)',
  'America/Mexico_City (UTC−06:00)',
  'America/Bogota (UTC−05:00)',
  'America/New_York (UTC−05:00)',
  'America/Halifax (UTC−04:00)',
  'America/Sao_Paulo (UTC−03:00)',
  'Atlantic/Azores (UTC−01:00)',
  'Etc/UTC (UTC+00:00)',
  'Europe/London (UTC+00:00)',
  'Africa/Lagos (UTC+01:00)',
  'Europe/Berlin (UTC+01:00)',
  'Europe/Madrid (UTC+01:00)',
  'Europe/Paris (UTC+01:00)',
  'Africa/Cairo (UTC+02:00)',
  'Africa/Johannesburg (UTC+02:00)',
  'Europe/Athens (UTC+02:00)',
  'Europe/Kyiv (UTC+02:00)',
  'Africa/Nairobi (UTC+03:00)',
  'Asia/Riyadh (UTC+03:00)',
  'Europe/Istanbul (UTC+03:00)',
  'Europe/Moscow (UTC+03:00)',
  'Asia/Dubai (UTC+04:00)',
  'Asia/Karachi (UTC+05:00)',
  'Asia/Tashkent (UTC+05:00)',
  'Asia/Colombo (UTC+05:30)',
  'Asia/Kolkata (UTC+05:30)',
  'Asia/Kathmandu (UTC+05:45)',
  'Asia/Dhaka (UTC+06:00)',
  'Asia/Yangon (UTC+06:30)',
  'Asia/Bangkok (UTC+07:00)',
  'Asia/Jakarta (UTC+07:00)',
  'Asia/Hong_Kong (UTC+08:00)',
  'Asia/Kuala_Lumpur (UTC+08:00)',
  'Asia/Manila (UTC+08:00)',
  'Asia/Shanghai (UTC+08:00)',
  'Asia/Singapore (UTC+08:00)',
  'Asia/Seoul (UTC+09:00)',
  'Asia/Tokyo (UTC+09:00)',
  'Australia/Brisbane (UTC+10:00)',
  'Australia/Sydney (UTC+10:00)',
  'Pacific/Auckland (UTC+12:00)',
];

/// Organization types offered on the sign-up form.
const List<String> organizationTypes = [
  'Enterprise',
  'Small Business',
  'Startup',
  'Non-profit',
  'Government',
  'Educational Institution',
  'Agency',
  'Partnership',
  'Sole Proprietorship',
];

/// Industry sectors, loosely following GICS.
const List<String> industries = [
  'Information Technology',
  'Software & SaaS',
  'Financial Services',
  'Banking & Insurance',
  'Healthcare & Life Sciences',
  'Pharmaceuticals',
  'Manufacturing',
  'Automotive',
  'Retail & E-commerce',
  'Consumer Goods',
  'Logistics & Supply Chain',
  'Construction & Real Estate',
  'Energy & Utilities',
  'Telecommunications',
  'Media & Entertainment',
  'Travel & Hospitality',
  'Education',
  'Professional Services',
  'Legal',
  'Agriculture',
  'Aerospace & Defense',
  'Public Sector',
  'Non-profit & NGO',
  'Other',
];

/// Head-count bands.
const List<String> companySizes = [
  '1-10',
  '11-50',
  '51-200',
  '201-500',
  '501-1000',
  '1001-5000',
  '5001-10000',
  '10000+',
];
