import 'package:flutter/material.dart';

import '../models/dashboard_models.dart';

/// DEMO DATA for the directory pages.
///
/// Split out of `repository.dart` purely for length — it is the same demo
/// dataset and is used only by `DemoDashboardRepository`. Replacing that class
/// with an HTTP one removes every reference to this file, so all mock data
/// still leaves the app in one step.
///
/// Names, companies and figures are invented but internally consistent: the
/// people who own projects here are the same people listed in [demoMembers],
/// and the customers projects belong to are the ones in [demoCustomers].
abstract final class DemoData {
  /// Everything is dated relative to one instant so the demo never drifts
  /// into an inconsistent state between calls.
  static List<Member> members(DateTime now) => [
        Member(
          id: 'u-1001',
          name: 'Vishnu Vardhan',
          email: 'vishnu.vardhan@thestackly.com',
          role: 'Administrator',
          department: 'Platform',
          status: AccountStatus.active,
          lastActive: now.subtract(const Duration(minutes: 4)),
          joined: DateTime(2022, 3, 14),
        ),
        Member(
          id: 'u-1002',
          name: 'Arun Kumar',
          email: 'arun.kumar@thestackly.com',
          role: 'Project Manager',
          department: 'Delivery',
          status: AccountStatus.active,
          lastActive: now.subtract(const Duration(minutes: 22)),
          joined: DateTime(2022, 7, 1),
        ),
        Member(
          id: 'u-1003',
          name: 'Priya Raman',
          email: 'priya.raman@thestackly.com',
          role: 'Engineering Lead',
          department: 'Engineering',
          status: AccountStatus.active,
          lastActive: now.subtract(const Duration(hours: 2)),
          joined: DateTime(2021, 11, 8),
        ),
        Member(
          id: 'u-1004',
          name: 'Meera Shah',
          email: 'meera.shah@thestackly.com',
          role: 'Account Manager',
          department: 'Customer Success',
          status: AccountStatus.active,
          lastActive: now.subtract(const Duration(hours: 5)),
          joined: DateTime(2023, 1, 23),
        ),
        Member(
          id: 'u-1005',
          name: 'Rahul Menon',
          email: 'rahul.menon@thestackly.com',
          role: 'Data Engineer',
          department: 'Engineering',
          status: AccountStatus.active,
          lastActive: now.subtract(const Duration(hours: 9)),
          joined: DateTime(2023, 5, 2),
        ),
        Member(
          id: 'u-1006',
          name: 'Kavya Nair',
          email: 'kavya.nair@thestackly.com',
          role: 'Business Analyst',
          department: 'Strategy',
          status: AccountStatus.active,
          lastActive: now.subtract(const Duration(days: 1)),
          joined: DateTime(2023, 9, 18),
        ),
        Member(
          id: 'u-1007',
          name: 'Daniel Okafor',
          email: 'daniel.okafor@thestackly.com',
          role: 'QA Engineer',
          department: 'Engineering',
          status: AccountStatus.inactive,
          lastActive: now.subtract(const Duration(days: 47)),
          joined: DateTime(2022, 10, 11),
        ),
        Member(
          id: 'u-1008',
          name: 'Sofia Marchetti',
          email: 'sofia.marchetti@thestackly.com',
          role: 'UX Designer',
          department: 'Design',
          status: AccountStatus.active,
          lastActive: now.subtract(const Duration(hours: 3)),
          joined: DateTime(2024, 2, 5),
        ),
        Member(
          id: 'u-1009',
          name: 'Thomas Bergstrom',
          email: 'thomas.bergstrom@thestackly.com',
          role: 'Finance Controller',
          department: 'Finance',
          status: AccountStatus.pending,
          lastActive: now.subtract(const Duration(days: 3)),
          joined: now.subtract(const Duration(days: 3)),
        ),
        Member(
          id: 'u-1010',
          name: 'Aisha Rahman',
          email: 'aisha.rahman@thestackly.com',
          role: 'Support Specialist',
          department: 'Customer Success',
          status: AccountStatus.active,
          lastActive: now.subtract(const Duration(minutes: 51)),
          joined: DateTime(2023, 6, 27),
        ),
        Member(
          id: 'u-1011',
          name: 'Lucas Fernandes',
          email: 'lucas.fernandes@thestackly.com',
          role: 'DevOps Engineer',
          department: 'Platform',
          status: AccountStatus.active,
          lastActive: now.subtract(const Duration(hours: 7)),
          joined: DateTime(2022, 12, 12),
        ),
        Member(
          id: 'u-1012',
          name: 'Hannah Whitfield',
          email: 'hannah.whitfield@thestackly.com',
          role: 'Marketing Lead',
          department: 'Marketing',
          status: AccountStatus.suspended,
          lastActive: now.subtract(const Duration(days: 12)),
          joined: DateTime(2021, 8, 30),
        ),
        Member(
          id: 'u-1013',
          name: 'Omar Haddad',
          email: 'omar.haddad@thestackly.com',
          role: 'Solutions Architect',
          department: 'Delivery',
          status: AccountStatus.active,
          lastActive: now.subtract(const Duration(hours: 1)),
          joined: DateTime(2023, 3, 6),
        ),
        Member(
          id: 'u-1014',
          name: 'Ingrid Larsen',
          email: 'ingrid.larsen@thestackly.com',
          role: 'Product Manager',
          department: 'Product',
          status: AccountStatus.pending,
          lastActive: now.subtract(const Duration(days: 2)),
          joined: now.subtract(const Duration(days: 2)),
        ),
      ];

  static List<Customer> customers(DateTime now) => [
        Customer(
          id: 'c-2001',
          company: 'Northwind Ltd',
          contact: 'Eleanor Vance',
          email: 'e.vance@northwind.com',
          industry: 'Logistics',
          manager: 'Meera Shah',
          status: AccountStatus.active,
          health: CustomerHealth.healthy,
          projects: 4,
          lastActivity: now.subtract(const Duration(hours: 3)),
          value: r'$420K',
        ),
        Customer(
          id: 'c-2002',
          company: 'Verdant Health',
          contact: 'Dr. Samuel Osei',
          email: 's.osei@verdanthealth.org',
          industry: 'Healthcare',
          manager: 'Meera Shah',
          status: AccountStatus.active,
          health: CustomerHealth.healthy,
          projects: 3,
          lastActivity: now.subtract(const Duration(hours: 8)),
          value: r'$310K',
        ),
        Customer(
          id: 'c-2003',
          company: 'Kestrel Finance',
          contact: 'Marcus Bright',
          email: 'm.bright@kestrelfin.com',
          industry: 'Financial Services',
          manager: 'Omar Haddad',
          status: AccountStatus.active,
          health: CustomerHealth.atRisk,
          projects: 2,
          lastActivity: now.subtract(const Duration(days: 6)),
          value: r'$580K',
        ),
        Customer(
          id: 'c-2004',
          company: 'Orion Logistics',
          contact: 'Rebecca Cho',
          email: 'r.cho@orionlog.com',
          industry: 'Logistics',
          manager: 'Arun Kumar',
          status: AccountStatus.active,
          health: CustomerHealth.healthy,
          projects: 5,
          lastActivity: now.subtract(const Duration(hours: 1)),
          value: r'$265K',
        ),
        Customer(
          id: 'c-2005',
          company: 'Solent Retail',
          contact: 'Grace Adeyemi',
          email: 'g.adeyemi@solentretail.co.uk',
          industry: 'Retail',
          manager: 'Aisha Rahman',
          status: AccountStatus.active,
          health: CustomerHealth.watch,
          projects: 2,
          lastActivity: now.subtract(const Duration(days: 2)),
          value: r'$190K',
        ),
        Customer(
          id: 'c-2006',
          company: 'Halcyon Energy',
          contact: 'Peter Lindqvist',
          email: 'p.lindqvist@halcyonenergy.se',
          industry: 'Energy',
          manager: 'Omar Haddad',
          status: AccountStatus.active,
          health: CustomerHealth.healthy,
          projects: 3,
          lastActivity: now.subtract(const Duration(hours: 14)),
          value: r'$735K',
        ),
        Customer(
          id: 'c-2007',
          company: 'Beacon Education',
          contact: 'Nadia Haq',
          email: 'n.haq@beaconedu.org',
          industry: 'Education',
          manager: 'Aisha Rahman',
          status: AccountStatus.active,
          health: CustomerHealth.watch,
          projects: 1,
          lastActivity: now.subtract(const Duration(days: 4)),
          value: r'$95K',
        ),
        Customer(
          id: 'c-2008',
          company: 'Meridian Manufacturing',
          contact: 'Tomas Novak',
          email: 't.novak@meridianmfg.cz',
          industry: 'Manufacturing',
          manager: 'Arun Kumar',
          status: AccountStatus.active,
          health: CustomerHealth.healthy,
          projects: 2,
          lastActivity: now.subtract(const Duration(days: 1)),
          value: r'$340K',
        ),
        Customer(
          id: 'c-2009',
          company: 'Lighthouse Insurance',
          contact: 'Claire Dubois',
          email: 'c.dubois@lighthouseins.fr',
          industry: 'Insurance',
          manager: 'Meera Shah',
          status: AccountStatus.inactive,
          health: CustomerHealth.atRisk,
          projects: 0,
          lastActivity: now.subtract(const Duration(days: 38)),
          value: r'$0',
        ),
        Customer(
          id: 'c-2010',
          company: 'Cobalt Media',
          contact: 'Jayden Brooks',
          email: 'j.brooks@cobaltmedia.tv',
          industry: 'Media',
          manager: 'Omar Haddad',
          status: AccountStatus.pending,
          health: CustomerHealth.watch,
          projects: 1,
          lastActivity: now.subtract(const Duration(days: 5)),
          value: r'$120K',
        ),
        Customer(
          id: 'c-2011',
          company: 'Summit Property Group',
          contact: 'Alina Petrova',
          email: 'a.petrova@summitpg.com',
          industry: 'Real Estate',
          manager: 'Arun Kumar',
          status: AccountStatus.active,
          health: CustomerHealth.healthy,
          projects: 2,
          lastActivity: now.subtract(const Duration(hours: 20)),
          value: r'$275K',
        ),
        Customer(
          id: 'c-2012',
          company: 'Pinewood Hospitality',
          contact: 'Marco Rossi',
          email: 'm.rossi@pinewoodhosp.it',
          industry: 'Hospitality',
          manager: 'Aisha Rahman',
          status: AccountStatus.active,
          health: CustomerHealth.watch,
          projects: 1,
          lastActivity: now.subtract(const Duration(days: 3)),
          value: r'$150K',
        ),
      ];

  static List<ProjectRecord> projects(DateTime now) => [
        ProjectRecord(
          id: 'p-3001',
          name: 'Atlas Migration',
          customer: 'Northwind Ltd',
          manager: 'Arun Kumar',
          team: const ['Priya Raman', 'Rahul Menon', 'Lucas Fernandes'],
          start: now.subtract(const Duration(days: 74)),
          end: now.add(const Duration(days: 12)),
          progress: .68,
          priority: Priority.high,
          status: ProjectStatus.inProgress,
        ),
        ProjectRecord(
          id: 'p-3002',
          name: 'Customer Portal 2.0',
          customer: 'Verdant Health',
          manager: 'Priya Raman',
          team: const ['Sofia Marchetti', 'Omar Haddad'],
          start: now.subtract(const Duration(days: 40)),
          end: now.add(const Duration(days: 26)),
          progress: .41,
          priority: Priority.medium,
          status: ProjectStatus.active,
        ),
        ProjectRecord(
          id: 'p-3003',
          name: 'Billing Consolidation',
          customer: 'Kestrel Finance',
          manager: 'Meera Shah',
          team: const ['Rahul Menon', 'Thomas Bergstrom'],
          start: now.subtract(const Duration(days: 96)),
          end: now.subtract(const Duration(days: 4)),
          progress: .23,
          priority: Priority.critical,
          status: ProjectStatus.atRisk,
        ),
        ProjectRecord(
          id: 'p-3004',
          name: 'Data Warehouse Refresh',
          customer: 'Orion Logistics',
          manager: 'Rahul Menon',
          team: const ['Priya Raman', 'Lucas Fernandes'],
          start: now.subtract(const Duration(days: 150)),
          end: now.subtract(const Duration(days: 3)),
          progress: 1,
          priority: Priority.medium,
          status: ProjectStatus.completed,
        ),
        ProjectRecord(
          id: 'p-3005',
          name: 'Mobile SDK Rollout',
          customer: 'Solent Retail',
          manager: 'Kavya Nair',
          team: const ['Sofia Marchetti', 'Daniel Okafor'],
          start: now.subtract(const Duration(days: 30)),
          end: now.add(const Duration(days: 40)),
          progress: .55,
          priority: Priority.low,
          status: ProjectStatus.onHold,
        ),
        ProjectRecord(
          id: 'p-3006',
          name: 'Grid Analytics Platform',
          customer: 'Halcyon Energy',
          manager: 'Omar Haddad',
          team: const ['Rahul Menon', 'Kavya Nair', 'Priya Raman'],
          start: now.subtract(const Duration(days: 20)),
          end: now.add(const Duration(days: 74)),
          progress: .18,
          priority: Priority.high,
          status: ProjectStatus.active,
        ),
        ProjectRecord(
          id: 'p-3007',
          name: 'Campus Enrolment Portal',
          customer: 'Beacon Education',
          manager: 'Priya Raman',
          team: const ['Sofia Marchetti'],
          start: now.add(const Duration(days: 9)),
          end: now.add(const Duration(days: 120)),
          progress: 0,
          priority: Priority.medium,
          status: ProjectStatus.pending,
        ),
        ProjectRecord(
          id: 'p-3008',
          name: 'Shop Floor Telemetry',
          customer: 'Meridian Manufacturing',
          manager: 'Arun Kumar',
          team: const ['Lucas Fernandes', 'Daniel Okafor'],
          start: now.subtract(const Duration(days: 60)),
          end: now.add(const Duration(days: 18)),
          progress: .72,
          priority: Priority.high,
          status: ProjectStatus.inProgress,
        ),
        ProjectRecord(
          id: 'p-3009',
          name: 'Claims Automation',
          customer: 'Lighthouse Insurance',
          manager: 'Meera Shah',
          team: const ['Rahul Menon'],
          start: now.subtract(const Duration(days: 210)),
          end: now.subtract(const Duration(days: 30)),
          progress: .85,
          priority: Priority.medium,
          status: ProjectStatus.onHold,
        ),
        ProjectRecord(
          id: 'p-3010',
          name: 'Streaming Rights Ledger',
          customer: 'Cobalt Media',
          manager: 'Omar Haddad',
          team: const ['Priya Raman', 'Thomas Bergstrom'],
          start: now.subtract(const Duration(days: 12)),
          end: now.add(const Duration(days: 96)),
          progress: .09,
          priority: Priority.low,
          status: ProjectStatus.active,
        ),
        ProjectRecord(
          id: 'p-3011',
          name: 'Tenant Insights Dashboard',
          customer: 'Summit Property Group',
          manager: 'Kavya Nair',
          team: const ['Sofia Marchetti', 'Omar Haddad'],
          start: now.subtract(const Duration(days: 88)),
          end: now.subtract(const Duration(days: 10)),
          progress: 1,
          priority: Priority.medium,
          status: ProjectStatus.completed,
        ),
        ProjectRecord(
          id: 'p-3012',
          name: 'Booking Engine Replatform',
          customer: 'Pinewood Hospitality',
          manager: 'Arun Kumar',
          team: const ['Lucas Fernandes', 'Priya Raman', 'Daniel Okafor'],
          start: now.subtract(const Duration(days: 55)),
          end: now.add(const Duration(days: 6)),
          progress: .61,
          priority: Priority.critical,
          status: ProjectStatus.inProgress,
        ),
      ];

  static List<TaskRecord> tasks(DateTime now) => [
        TaskRecord(
          id: 't-4001',
          name: 'Finalise data migration cutover plan',
          project: 'Atlas Migration',
          assignee: 'Arun Kumar',
          priority: Priority.critical,
          stage: TaskStage.inProgress,
          due: now.add(const Duration(days: 2)),
          progress: .7,
          created: now.subtract(const Duration(days: 14)),
        ),
        TaskRecord(
          id: 't-4002',
          name: 'Review Q3 access audit findings',
          project: 'Billing Consolidation',
          assignee: 'Meera Shah',
          priority: Priority.high,
          stage: TaskStage.review,
          due: now.subtract(const Duration(days: 1)),
          progress: .9,
          created: now.subtract(const Duration(days: 20)),
        ),
        TaskRecord(
          id: 't-4003',
          name: 'Ship portal design tokens',
          project: 'Customer Portal 2.0',
          assignee: 'Sofia Marchetti',
          priority: Priority.medium,
          stage: TaskStage.todo,
          due: now.add(const Duration(days: 6)),
          progress: 0,
          created: now.subtract(const Duration(days: 5)),
        ),
        TaskRecord(
          id: 't-4004',
          name: 'Retire legacy billing batch jobs',
          project: 'Billing Consolidation',
          assignee: 'Rahul Menon',
          priority: Priority.high,
          stage: TaskStage.inProgress,
          due: now.add(const Duration(days: 9)),
          progress: .45,
          created: now.subtract(const Duration(days: 11)),
        ),
        TaskRecord(
          id: 't-4005',
          name: 'Publish SDK release notes',
          project: 'Mobile SDK Rollout',
          assignee: 'Kavya Nair',
          priority: Priority.low,
          stage: TaskStage.completed,
          due: now.subtract(const Duration(days: 4)),
          progress: 1,
          created: now.subtract(const Duration(days: 18)),
        ),
        TaskRecord(
          id: 't-4006',
          name: 'Provision telemetry ingest cluster',
          project: 'Shop Floor Telemetry',
          assignee: 'Lucas Fernandes',
          priority: Priority.high,
          stage: TaskStage.inProgress,
          due: now.add(const Duration(days: 4)),
          progress: .6,
          created: now.subtract(const Duration(days: 9)),
        ),
        TaskRecord(
          id: 't-4007',
          name: 'Await customer sign-off on data schema',
          project: 'Grid Analytics Platform',
          assignee: 'Omar Haddad',
          priority: Priority.critical,
          stage: TaskStage.blocked,
          due: now.subtract(const Duration(days: 2)),
          progress: .3,
          created: now.subtract(const Duration(days: 16)),
        ),
        TaskRecord(
          id: 't-4008',
          name: 'Accessibility audit on booking flow',
          project: 'Booking Engine Replatform',
          assignee: 'Sofia Marchetti',
          priority: Priority.medium,
          stage: TaskStage.review,
          due: now.add(const Duration(days: 3)),
          progress: .8,
          created: now.subtract(const Duration(days: 7)),
        ),
        TaskRecord(
          id: 't-4009',
          name: 'Load-test rights ledger API',
          project: 'Streaming Rights Ledger',
          assignee: 'Rahul Menon',
          priority: Priority.medium,
          stage: TaskStage.todo,
          due: now.add(const Duration(days: 15)),
          progress: 0,
          created: now.subtract(const Duration(days: 3)),
        ),
        TaskRecord(
          id: 't-4010',
          name: 'Migrate enrolment records to staging',
          project: 'Campus Enrolment Portal',
          assignee: 'Priya Raman',
          priority: Priority.low,
          stage: TaskStage.todo,
          due: now.add(const Duration(days: 21)),
          progress: 0,
          created: now.subtract(const Duration(days: 2)),
        ),
        TaskRecord(
          id: 't-4011',
          name: 'Close out warehouse refresh handover',
          project: 'Data Warehouse Refresh',
          assignee: 'Rahul Menon',
          priority: Priority.low,
          stage: TaskStage.completed,
          due: now.subtract(const Duration(days: 6)),
          progress: 1,
          created: now.subtract(const Duration(days: 30)),
        ),
        TaskRecord(
          id: 't-4012',
          name: 'Renegotiate Kestrel support SLA',
          project: 'Billing Consolidation',
          assignee: 'Meera Shah',
          priority: Priority.critical,
          stage: TaskStage.inProgress,
          due: now.add(const Duration(days: 1)),
          progress: .5,
          created: now.subtract(const Duration(days: 8)),
        ),
        TaskRecord(
          id: 't-4013',
          name: 'Draft tenant insights user guide',
          project: 'Tenant Insights Dashboard',
          assignee: 'Kavya Nair',
          priority: Priority.low,
          stage: TaskStage.completed,
          due: now.subtract(const Duration(days: 12)),
          progress: 1,
          created: now.subtract(const Duration(days: 25)),
        ),
        TaskRecord(
          id: 't-4014',
          name: 'Fix SSO redirect loop on mobile Safari',
          project: 'Customer Portal 2.0',
          assignee: 'Lucas Fernandes',
          priority: Priority.critical,
          stage: TaskStage.blocked,
          due: now.subtract(const Duration(days: 3)),
          progress: .25,
          created: now.subtract(const Duration(days: 10)),
        ),
        TaskRecord(
          id: 't-4015',
          name: 'QA regression pass on telemetry alerts',
          project: 'Shop Floor Telemetry',
          assignee: 'Daniel Okafor',
          priority: Priority.medium,
          stage: TaskStage.todo,
          due: now.add(const Duration(days: 8)),
          progress: 0,
          created: now.subtract(const Duration(days: 4)),
        ),
      ];

  static List<UpcomingItem> upcoming(DateTime now) => [
        UpcomingItem(
          title: 'Kestrel SLA renegotiation closes',
          context: 'Billing Consolidation',
          due: now.add(const Duration(days: 1)),
          kind: UpcomingKind.deadline,
          priority: Priority.critical,
        ),
        UpcomingItem(
          title: 'Data migration cutover',
          context: 'Atlas Migration',
          due: now.add(const Duration(days: 2)),
          kind: UpcomingKind.milestone,
          priority: Priority.critical,
        ),
        UpcomingItem(
          title: 'Booking engine go-live review',
          context: 'Pinewood Hospitality',
          due: now.add(const Duration(days: 6)),
          kind: UpcomingKind.meeting,
          priority: Priority.high,
        ),
        UpcomingItem(
          title: 'Portal design tokens handoff',
          context: 'Customer Portal 2.0',
          due: now.add(const Duration(days: 6)),
          kind: UpcomingKind.task,
          priority: Priority.medium,
        ),
        UpcomingItem(
          title: 'Shop floor telemetry phase 2 start',
          context: 'Meridian Manufacturing',
          due: now.add(const Duration(days: 18)),
          kind: UpcomingKind.milestone,
          priority: Priority.high,
        ),
        UpcomingItem(
          title: 'Quarterly business review — Halcyon',
          context: 'Halcyon Energy',
          due: now.add(const Duration(days: 21)),
          kind: UpcomingKind.meeting,
          priority: Priority.medium,
        ),
      ];

  static ReportsData reports(DateTime now) => ReportsData(
        kpis: const [
          Kpi(
            label: 'Total Revenue',
            value: r'$4.86M',
            icon: Icons.payments_outlined,
            changePercent: 14.2,
            caption: r'$4.26M previous year',
          ),
          Kpi(
            label: 'Customer Growth',
            value: '+18.4%',
            icon: Icons.trending_up_outlined,
            changePercent: 3.1,
            caption: '12 new logos this quarter',
          ),
          Kpi(
            label: 'Project Completion',
            value: '87.5%',
            icon: Icons.fact_check_outlined,
            changePercent: 5.6,
            caption: 'On-time delivery rate',
          ),
          Kpi(
            label: 'Task Completion',
            value: '92.1%',
            icon: Icons.task_alt_outlined,
            changePercent: -1.8,
            caption: 'Closed within sprint',
          ),
          Kpi(
            label: 'Team Productivity',
            value: '81 pts',
            icon: Icons.speed_outlined,
            changePercent: 6.9,
            caption: 'Avg. velocity per sprint',
          ),
        ],
        revenue: const PerformanceSeries(
          labels: [
            'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', //
            'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
          ],
          values: [
            288, 312, 305, 341, 368, 355, //
            392, 410, 438, 452, 471, 508,
          ],
        ),
        customerGrowth: const PerformanceSeries(
          labels: [
            'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', //
            'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
          ],
          values: [
            2740, 2795, 2846, 2903, 2951, 3004, //
            3062, 3098, 3140, 3176, 3199, 3214,
          ],
        ),
        taskCompletion: const [
          (label: 'W1', active: 148, inactive: 22),
          (label: 'W2', active: 162, inactive: 18),
          (label: 'W3', active: 139, inactive: 31),
          (label: 'W4', active: 175, inactive: 14),
          (label: 'W5', active: 158, inactive: 26),
          (label: 'W6', active: 181, inactive: 12),
        ],
        teamProductivity: const [
          (name: 'Priya Raman', delivered: 47, utilisation: .92),
          (name: 'Rahul Menon', delivered: 41, utilisation: .88),
          (name: 'Lucas Fernandes', delivered: 38, utilisation: .81),
          (name: 'Sofia Marchetti', delivered: 34, utilisation: .76),
          (name: 'Omar Haddad', delivered: 29, utilisation: .71),
          (name: 'Daniel Okafor', delivered: 22, utilisation: .58),
        ],
        // Reuses ProjectStatus purely as a (label, colour) pair for the donut.
        industryMix: const [
          (status: ProjectStatus.inProgress, count: 2), // Logistics
          (status: ProjectStatus.completed, count: 2), // Healthcare
          (status: ProjectStatus.pending, count: 3), // Financial Services
          (status: ProjectStatus.atRisk, count: 2), // Retail
          (status: ProjectStatus.onHold, count: 3), // Other
        ],
        projectMix: const [
          (status: ProjectStatus.completed, count: 2),
          (status: ProjectStatus.inProgress, count: 3),
          (status: ProjectStatus.active, count: 3),
          (status: ProjectStatus.onHold, count: 2),
          (status: ProjectStatus.atRisk, count: 1),
          (status: ProjectStatus.pending, count: 1),
        ],
      );

  /// Labels for [ReportsData.industryMix], which reuses ProjectStatus colours.
  static const industryLabels = [
    'Logistics',
    'Healthcare',
    'Financial Services',
    'Retail',
    'Other',
  ];
}
